# -*- coding: utf-8 -*-
# """MiniProject.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1_eM6bKAUgUpD7ieqXNs5JuGzGor2kaZs
# """

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, f1_score, precision_score, recall_score,
                             mean_absolute_error, mean_squared_error, r2_score,
                             confusion_matrix, roc_curve, auc)

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from imblearn.over_sampling import SMOTE

import pickle

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dataset.csv')
df.isnull().sum()

df = df.drop(columns=['Unnamed: 0'], errors='ignore')

# Paper says these don’t affect prediction
df = df.drop(columns=['track_id', 'artists', 'album_name', 'track_name', 'track_genre'], errors='ignore')
df.shape

df = df.dropna()
print("Shape after removing NaN:", df.shape)

df['explicit'] = df['explicit'].map({'True':1, 'False':0}).fillna(0)
# put graphs here

sns.countplot(x='explicit', data=df)
plt.show()

sns.countplot(data=df, x="speechiness")

sns.countplot(x='popularity', data=df)
plt.show()

sns.countplot(x='tempo', data=df)
plt.show()

sns.histplot(x='tempo', data=df)
plt.show()

sns.boxplot(x=df["energy"])



df['is_popular'] = (df['popularity'] >= 52).astype(int)
df.shape

X = df.drop(columns=['popularity', 'is_popular'])
y_class = df['is_popular']
y_reg = df['popularity']

X_train, X_test, y_train_c, y_test_c = train_test_split(X, y_class, test_size=0.2, random_state=42)
_, _, y_train_r, y_test_r = train_test_split(X, y_reg, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train_c)

models_c = {
    "Logistic": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(probability=True)
}

results_c = {}

for name, model in models_c.items():
    model.fit(X_train_sm, y_train_sm)
    y_pred = model.predict(X_test)

    results_c[name] = {
        "Accuracy": accuracy_score(y_test_c, y_pred),
        "Precision": precision_score(y_test_c, y_pred),
        "Recall": recall_score(y_test_c, y_pred),
        "F1": f1_score(y_test_c, y_pred)
    }

df_results_c = pd.DataFrame(results_c).T
df_results_c

models_r = {
    "Linear": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor()
}

results_r = {}

for name, model in models_r.items():
    model.fit(X_train, y_train_r)
    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test_r, y_pred)
    rmse = np.sqrt(mse)

    results_r[name] = {
        "MAE": mean_absolute_error(y_test_r, y_pred),
        "MSE": mse,
        "RMSE": rmse,
        "R2": r2_score(y_test_r, y_pred)
    }

df_results_r = pd.DataFrame(results_r).T
df_results_r

# Classification (with SMOTE data)
best_clf = RandomForestClassifier(random_state=42)
best_clf.fit(X_train_sm, y_train_sm)

best_reg = RandomForestRegressor(random_state=42)
best_reg.fit(X_train, y_train_r)

y_pred_c = best_clf.predict(X_test)
y_prob_c = best_clf.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test_c, y_pred_c))
print("Precision:", precision_score(y_test_c, y_pred_c))
print("Recall:", recall_score(y_test_c, y_pred_c))
print("F1 Score:", f1_score(y_test_c, y_pred_c))

cm = confusion_matrix(y_test_c, y_pred_c)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix - Random Forest")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

y_pred_r = best_reg.predict(X_test)

mse = mean_squared_error(y_test_r, y_pred_r)
rmse = np.sqrt(mse)

print("MAE:", mean_absolute_error(y_test_r, y_pred_r))
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2_score(y_test_r, y_pred_r))

imp_df = pd.DataFrame({
    "Feature Name": X.columns,   # or X_train.columns if still DataFrame
    "Importance": best_clf.feature_importances_
})

fi = imp_df.sort_values(by="Importance", ascending=False)

plt.figure(figsize=(10,8))
sns.barplot(data=fi, x='Importance', y='Feature Name')

plt.title('Feature Importance of Attributes', fontsize=18)
plt.xlabel('Importance', fontsize=16)
plt.ylabel('Feature Name', fontsize=16)

plt.show()

def predict_song(best_clf, best_reg, scaler):
    print("🎵 Enter Song Features:\n")

    duration = float(input("Duration (ms): "))
    explicit = int(input("Explicit (0 = No, 1 = Yes): "))
    danceability = float(input("Danceability (0-1): "))
    energy = float(input("Energy (0-1): "))
    key = float(input("Key (0-11): "))
    loudness = float(input("Loudness (negative dB): "))
    mode = float(input("Mode (0 = Minor, 1 = Major): "))
    speechiness = float(input("Speechiness (0-1): "))
    acousticness = float(input("Acousticness (0-1): "))
    instrumentalness = float(input("Instrumentalness (0-1): "))
    liveness = float(input("Liveness (0-1): "))
    valence = float(input("Valence (0-1): "))
    tempo = float(input("Tempo (BPM): "))
    time_signature = float(input("Time Signature (e.g., 4): "))

    input_data = np.array([[duration, explicit, danceability, energy, key,
                            loudness, mode, speechiness, acousticness,
                            instrumentalness, liveness, valence,
                            tempo, time_signature]])

    input_scaled = scaler.transform(input_data)

    pred_class = best_clf.predict(input_scaled)[0]
    prob = best_clf.predict_proba(input_scaled)[0]

    pred_score = best_reg.predict(input_scaled)[0]

    print("\n--- 🎯 Prediction Result ---")

    if pred_class == 1:
        print("🟢 Song is likely to be POPULAR")
    else:
        print("🔴 Song is NOT likely to be popular")

    print(f"Confidence: {round(max(prob)*100, 2)}%")

    print(f"\n📈 Predicted Popularity Score: {round(pred_score, 2)}")

predict_song(best_clf, best_reg, scaler)

